[package]
name = "javy"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "javy"

[dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
which = "4.2"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"
binaryen = { git = "https://github.com/pepyakin/binaryen-rs", rev = "5b5e477" }

[dev-dependencies]
wasmtime = "0.29"
wasmtime-wasi = "0.29"
rmp-serde = "0.15"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }

