name: ci

on:
  push:
    branches:
      - main
    tags:
      - suborbital-v*
  pull_request:

jobs:
  test:
    if: 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - name: Install wasmtime-cli
        run: cargo install --version 0.35.3 wasmtime-cli

      - name: Install cargo-wasi
        run: cargo install cargo-wasi

      - name: Tests
        run: make tests

      - name: Lint
        run: make fmt

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - run: make core

      - name: Upload core binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: engine
          path: target/wasm32-wasi/release/javy_core.wasm

  cli:
    needs:  core
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - arm64
          - amd64
        include:
        - build: arm64
          os: buildjet-2vcpu-ubuntu-2204-arm
          target: aarch64-unknown-linux-gnu
        - build: amd64
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: engine
          path: crates/cli/

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - run: cargo build --release --package javy
        env:
          JAVY_ENGINE_PATH: javy_core.wasm

      - uses: actions/upload-artifact@v3
        with:
          name: javy-${{ matrix.build }}-linux
          path: target/release/javy

  bin:
    needs: [cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: bins/

      - run: gzip -k -f bins/javy-arm64-linux/javy && mv bins/javy-arm64-linux/javy.gz javy-aarch64-linux.gz
      - run: gzip -k -f bins/javy-amd64-linux/javy && mv bins/javy-amd64-linux/javy.gz javy-x86_64-linux.gz

      - if: startsWith(github.ref, 'refs/tags/suborbital-v')
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["javy-*-linux.gz"]'

  image:
    needs: [cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2

      - uses: actions/download-artifact@v3
        with:
          path: bins/

      - if: ${{ startsWith(github.ref, 'refs/tags/suborbital-v') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: ghcr.io/suborbital/javy
          tags: |
            type=match,pattern=suborbital-(v.*),group=1
          flavor: |
            latest=auto

      # Build the image on pulls, main
      - if: ${{ !startsWith(github.ref, 'refs/tags/suborbital-v') }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          context: .
          file: Dockerfile-ci
          load: true
          push: false
          tags: ghcr.io/suborbital/javy:dev
      - if: ${{ !startsWith(github.ref, 'refs/tags/suborbital-v') }}
        run: docker run -i --rm ghcr.io/suborbital/javy:dev /usr/local/bin/javy --version

      # Build and push the image on release tags
      - if: ${{ startsWith(github.ref, 'refs/tags/suborbital-v') }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          context: .
          file: Dockerfile-ci
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
