name: ci

on:
  push:
    branches:
      - main
    tags:
      - suborbital-v*
  pull_request:

jobs:
  test:
    if: 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - name: Install wasmtime-cli
        run: cargo install --version 0.35.3 wasmtime-cli

      - name: Install cargo-wasi
        run: cargo install cargo-wasi

      - name: Tests
        run: make tests

      - name: Lint
        run: make fmt

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - run: make core

      - name: Upload core binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: engine
          path: target/wasm32-wasi/release/javy_core.wasm

  cli:
    needs:  core
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        include:
          - arch: arm64
            os: buildjet-2vcpu-ubuntu-2204-arm
            target: aarch64-unknown-linux-gnu
          - arch: amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: engine
          path: crates/cli/

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - run: cargo build --release --package javy
        env:
          JAVY_ENGINE_PATH: javy_core.wasm

      - uses: actions/upload-artifact@v3
        with:
          name: javy-${{ matrix.arch }}-linux
          path: target/release/javy

  image:
    needs: [cli]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - arm64
          - amd64
        include:
          - arch: arm64
            os: buildjet-2vcpu-ubuntu-2204-arm
          - arch: amd64
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - if: ${{ startsWith(github.ref, 'refs/tags/suborbital-v') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: ghcr.io/suborbital/javy
          tags: |
            type=match,pattern=suborbital-(v.*),group=1
          flavor: |
            latest=false
            suffix=-${{ matrix.arch }}

      # Build the image on pulls, main
      - name: Build javy image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          file: Dockerfile
          load: true
          push: false
          tags: ghcr.io/suborbital/javy:dev

      - run: docker run -i --rm ghcr.io/suborbital/javy:dev /usr/local/bin/javy --version

      # Build and push the image on release tags
      - name: Build and push javy image
        if: ${{ startsWith(github.ref, 'refs/tags/suborbital-v') }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  manifest:
    if: startsWith(github.ref, 'refs/tags/suborbital-v')
    needs: [image]
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: release
        run: |
          tag=${GITHUB_REF#"refs/tags/suborbital-"}
          echo $tag
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - uses: Noelware/docker-manifest-action@v0.2.3
        with:
          base-image: ghcr.io/suborbital/javy:${{ steps.release.outputs.tag }}
          extra-images: ghcr.io/suborbital/javy:latest,ghcr.io/suborbital/javy:${{ steps.release.outputs.tag }}-amd64,ghcr.io/suborbital/javy:${{ steps.release.outputs.tag }}-arm64
          push: true

  bin:
    needs: [cli, image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: bins/

      - run: gzip -k -f bins/javy-arm64-linux/javy && mv bins/javy-arm64-linux/javy.gz javy-aarch64-linux.gz
      - run: gzip -k -f bins/javy-amd64-linux/javy && mv bins/javy-amd64-linux/javy.gz javy-x86_64-linux.gz

      - if: startsWith(github.ref, 'refs/tags/suborbital-v')
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["javy-*-linux.gz"]'
